# Generated by Django 3.1.4 on 2021-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210303_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='placed',
        ),
    ]
